# 1. Create a 3x3x3 array with random values 

In [1]:
import numpy as np
a=np.empty((3,3,3))
print("The Array is-")
print(a)
print("The Shape of Array is-")
print(a.shape)

The Array is-
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]
The Shape of Array is-
(3, 3, 3)


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [2]:
b=np.zeros((5,5))#creates a zeros matrix of specified order
print("Initial Matrix-")
print(b)
for i in range(len(b)):
    for j in range(len(b)):
        if(i==j+1):
            b[i][j]=i
print("Final Matrix-")
print(b)    

Initial Matrix-
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Final Matrix-
[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

Checkerboard pattern consist of black and white color alternatively in 8X8 grid, here BLACK is represented as 0 and WHITE is represented as 255.

In [3]:
c=np.zeros((8,8))#creates a zeros matrix of specified order 
print("Initial Matrix-")
print(c)
for i in range(len(c)):
    for j in range(len(c)):
        if(j%2!=0):
            c[i][j]=255
print("Final Matrix-")
print(c) 

Initial Matrix-
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
Final Matrix-
[[  0. 255.   0. 255.   0. 255.   0. 255.]
 [  0. 255.   0. 255.   0. 255.   0. 255.]
 [  0. 255.   0. 255.   0. 255.   0. 255.]
 [  0. 255.   0. 255.   0. 255.   0. 255.]
 [  0. 255.   0. 255.   0. 255.   0. 255.]
 [  0. 255.   0. 255.   0. 255.   0. 255.]
 [  0. 255.   0. 255.   0. 255.   0. 255.]
 [  0. 255.   0. 255.   0. 255.   0. 255.]]


# 4. Normalize a 5x5 random matrix

In [4]:
d=np.random.randn(5,5)#creates a matrix of specified filled with random numbers
print("The random matrix is-")
print(d)
normal=np.linalg.norm(d)#computes the norm of the given matrix 
print("The norm value of random matrix is-")
print(normal)
e=np.divide(d,normal)#computes the normalized matrix
print("The normalized random mattrix is-")
print(e)

The random matrix is-
[[ 0.32634637 -1.98620691 -0.96714063  0.75524581 -0.08253727]
 [-1.21912115  0.67684441 -0.08071143 -1.55029721 -0.82060556]
 [-0.63970837 -0.54989392  0.08288539 -1.02202213 -0.25706886]
 [ 0.82890579 -0.65246618  0.44546236  1.21519375 -0.02802947]
 [-0.92810097  0.94890165  0.67294595  0.12406001  0.48246526]]
The norm value of random matrix is-
4.203856321705682
The normalized random mattrix is-
[[ 0.07763024 -0.4724726  -0.23006034  0.17965548 -0.0196337 ]
 [-0.29000067  0.1610056  -0.01919938 -0.36877978 -0.19520305]
 [-0.1521718  -0.13080702  0.01971651 -0.24311538 -0.06115072]
 [ 0.19717748 -0.15520658  0.10596517  0.28906643 -0.00666756]
 [-0.22077371  0.22572171  0.16007825  0.029511    0.11476731]]


# 5.  How to find common values between two arrays?

In [5]:
f=np.array([1,2,3,4,5])
print("The 1st array is-")
print(f)
g=np.array([2,4,6,8,10])
print("The 2nd array is-")
print(g)
com_values=np.intersect1d(f,g)
print("Common values between two arrays are-")
print(com_values)

The 1st array is-
[1 2 3 4 5]
The 2nd array is-
[ 2  4  6  8 10]
Common values between two arrays are-
[2 4]


# 6.How to get the dates of yesterday, today and tomorrow?

In [4]:
yesterday =np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday's Date: ",yesterday)
today= np.datetime64('today', 'D')
print("Today's Date: ",today)
tomorrow= np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow's Date: ",tomorrow)

Yestraday's Date:  2020-07-26
Today's Date:  2020-07-27
Tomorrow's Date:  2020-07-28


# 7. Consider two random array A and B, check if they are equal

In [5]:
h=np.array([1,2,3])
i=np.array([1,2,3])
comparison = h == i
equal_arrays = comparison.all()#compare two arrays and returns boolean expression
print("Output is True if two arrays are equal")
print("Output is False if two arrays are equal")
print("Output:",equal_arrays)

Output is True if two arrays are equal
Output is False if two arrays are equal
Output: True


In [8]:
h=np.array([1,2,3])
i=np.array([4,5,6])
comparison = h == i
equal_arrays = comparison.all()
print("Output is True if two arrays are equal")
print("Output is False if two arrays are equal")
print("Output:",equal_arrays)

Output is True if two arrays are equal
Output is False if two arrays are equal
Output: False


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [6]:
vec=np.random.randn(10,1)#creates a random vector of given order
print("The random vector is-")
print(vec)
max_val=np.amax(vec)#computes the maximum value from a given vector
print("The maximum value in the vector is-")
print(max_val)
loc=np.where(vec==max_val)#find the index of the maximum value
vec[loc]=0
print("The new vector is-")
print(vec)

The random vector is-
[[-0.19092239]
 [-0.97642269]
 [-1.17059212]
 [-2.31871184]
 [ 0.68903893]
 [-0.80808394]
 [ 0.06321521]
 [-1.07484433]
 [ 0.36242516]
 [ 1.4643328 ]]
The maximum value in the vector is-
1.4643328005076437
The new vector is-
[[-0.19092239]
 [-0.97642269]
 [-1.17059212]
 [-2.31871184]
 [ 0.68903893]
 [-0.80808394]
 [ 0.06321521]
 [-1.07484433]
 [ 0.36242516]
 [ 0.        ]]


# 9. How to print all the values of an array?

In [7]:
l=np.random.randn(3,)#creates a random array of given order
print("The array is:")
print(l)
for i in range(len(l)):
    print("The element at index(",i,") is:",l[i])

The array is:
[0.12482649 0.60368961 1.14699166]
The element at index( 0 ) is: 0.12482648961120893
The element at index( 1 ) is: 0.6036896105623559
The element at index( 2 ) is: 1.1469916609935855


In [22]:
l=np.random.randn(3,3)#creates a random array of given order
print("The array is:")
print(l)
for i in range(len(l)):
    for j in range(len(l)):
        print("The element at index(",i,",",j,")is:",l[i][j])

The array is:
[[-1.65608512 -1.29934123 -0.85449239]
 [ 0.42846595  0.36934972 -1.60745369]
 [-0.57658046 -1.14348038 -2.13782552]]
The element at index( 0 , 0 )is: -1.6560851161691763
The element at index( 0 , 1 )is: -1.2993412343383661
The element at index( 0 , 2 )is: -0.8544923894421872
The element at index( 1 , 0 )is: 0.4284659498060725
The element at index( 1 , 1 )is: 0.36934972478169953
The element at index( 1 , 2 )is: -1.6074536948681089
The element at index( 2 , 0 )is: -0.5765804584822585
The element at index( 2 , 1 )is: -1.143480381396333
The element at index( 2 , 2 )is: -2.137825517177939


# 10.Subtract the mean of each row of a matrix

In [12]:
arr=np.random.randn(3,3)#creates a random matrix of given order
print("The matrix is-")
print(arr)
print("The mean value of each row is-")
arr1=np.mean(arr,axis=1)#computes the mean of each row
print(arr1)
arr2=arr-arr1
print("The matrix after the mean is subtracted-")
print(arr2)

The matrix is-
[[-0.06546481  1.05471028 -1.16529538]
 [ 1.8850171  -1.00572427  0.20200482]
 [-0.23470266 -0.95281717 -0.81627792]]
The mean value of each row is-
[-0.0586833   0.36043255 -0.66793258]
The matrix after the mean is subtracted-
[[-0.00678151  0.69427773 -0.4973628 ]
 [ 1.9437004  -1.36615682  0.86993741]
 [-0.17601936 -1.31324972 -0.14834534]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [8]:
import numpy as np 
Z = np.random.randn(10,1)#creates a random vector of given order
print("The original vector is:")
print(Z)
I=np.random.randint(0,len(Z),4)#generates 4 random integers in a specified range,used as index values
print("The Index values obtained are:")
print(I)
J=np.unique(I,axis=0)#removes the duplicate values
print("The final unique index values are:")
print(J)
print("Final vector after adding 1 to corresponding elements at the specified indices:")
np.add.at(Z,J,1)#Adds 1 to the elements in given vector (Z) at the specified index values(I)
print(Z)

The original vector is:
[[ 0.95609892]
 [ 1.24800646]
 [-0.13465815]
 [ 0.51045258]
 [ 1.36462124]
 [ 0.8276065 ]
 [-0.1097297 ]
 [ 0.56927747]
 [-0.94317713]
 [-1.0542363 ]]
The Index values obtained are:
[4 1 1 6]
The final unique index values are:
[1 4 6]
Final vector after adding 1 to corresponding elements at the specified indices:
[[ 0.95609892]
 [ 2.24800646]
 [-0.13465815]
 [ 0.51045258]
 [ 2.36462124]
 [ 0.8276065 ]
 [ 0.8902703 ]
 [ 0.56927747]
 [-0.94317713]
 [-1.0542363 ]]


# 12.How to get the diagonal of a dot product?

In [15]:
u=np.random.randn(3,3)#creates a random matrix of given order
print("The first 3X3 array is- ")
print(u)
v=np.random.randn(3,3)
print("The second 3X3 array is- ")
print(v)
w=np.dot(u,v)#computes the dot product of two given matrices
print("The corresponding dot product is- ")
print(w)
z=np.diag(w)#choose the diagnol elements of given matrix
print("The corresponding diagnol elements are- ")
print(z)

The first 3X3 array is- 
[[-0.44017459  1.04916042 -0.07217374]
 [-0.87778766 -1.13790972  2.14978188]
 [ 0.43349028 -0.90422856  1.4632639 ]]
The second 3X3 array is- 
[[ 2.87612238  1.45200194  1.19952257]
 [ 0.8621398   0.08849527 -2.19494928]
 [-0.01380654 -1.84904567  0.27609321]]
The corresponding dot product is- 
[[-0.36047657 -0.41283609 -2.85077994]
 [-3.53534304 -5.3502939   2.03826818]
 [ 0.44699703 -2.15623301  2.90871442]]
The corresponding diagnol elements are- 
[-0.36047657 -5.3502939   2.90871442]


# 13.How to find the most frequent value in an array?

In [16]:
k=np.array([1,2,3,3,5,3,6,6,7,6,6,8])
np.argmax(np.bincount(k))#finds the value that is repeated maximum number of times in a given array

6

# 14.How to get the n largest values of an array

In [17]:
M=np.arange(1000)#generates a sequential array with numbers 0 to 999
np.random.shuffle(M)
n=int(input("Enter the value of n:"))
print("The",n,"largest value of the array are:")
print (M[np.argpartition(-M,n)[:n]])#prints the n largest values in the specified array

Enter the value of n:4
The 4 largest value of the array are:
[998 999 997 996]


# 15.How to create a record array from a regular array?

In [9]:
reg_arr = np.array([["Pranjul", 88.5, 90],["Manjeet", 87, 99],["Abdul", 85.5, 91]])#generates a 2D array
print("Original array:")
print(reg_arr)
print("\nRecord array:")
rec_arr = np.core.records.fromarrays(reg_arr.T,names='col1, col2, col3',formats = 'S80, f8, i8')# generates a reccord array
print(rec_arr)
type(rec_arr)

Original array:
[['Pranjul' '88.5' '90']
 ['Manjeet' '87' '99']
 ['Abdul' '85.5' '91']]

Record array:
[(b'Pranjul', 88.5, 90) (b'Manjeet', 87. , 99) (b'Abdul', 85.5, 91)]


numpy.recarray